---
- name: Restart traefik
  community.docker.docker_compose_v2:
    project_src: "{{ config_dir }}/traefik/"
    build: false
    state: restarted
  become: false

- name: Restart pi-hole
  community.docker.docker_compose_v2:
    project_src: "{{ config_dir }}/pi-hole/"
    build: never
    state: restarted
  become: false

- name: Restart internet-monitoring
  community.docker.docker_compose_v2:
    project_src: "{{ config_dir }}/internet-monitoring/"
    build: never
    state: restarted
  become: false

- name: Restart shelly-plug-prometheus
  community.docker.docker_compose_v2:
    project_src: "{{ config_dir }}/shelly-plug-prometheus/"
    build: never
    state: restarted
  become: false

- name: Restart starlink-exporter
  community.docker.docker_compose_v2:
    project_src: "{{ config_dir }}/starlink-exporter/"
    build: never
    state: restarted
  become: false

- name: Restart influxdb
  community.docker.docker_compose_v2:
    project_src: "{{ config_dir }}/influxdb/"
    build: never
    state: restarted
  become: false

- name: Restart unifi
  community.docker.docker_compose_v2:
    project_src: "{{ config_dir }}/unifi/"
    build: never
    state: restarted
  become: false

- name: Restart node-red
  community.docker.docker_compose_v2:
    project_src: "{{ config_dir }}/node-red/"
    build: never
    state: restarted
  become: false
