---
- name: Ensure mqtt directory exists.
  ansible.builtin.file:
    path: "{{ config_dir }}/mqtt"
    state: directory
    mode: 0755
  become: false

- name: Copy mqtt config to Pi.
  ansible.builtin.template:
    src: configs/mqtt/mosquitto.conf
    dest: "{{ config_dir }}/mqtt/mosquitto.conf"
    mode: "0640"

- name: Copy mqtt docker-compose template to Pi.
  ansible.builtin.template:
    src: templates/mqtt-docker-compose.yml.j2
    dest: "{{ config_dir }}/mqtt/docker-compose.yml"
    mode: "0640"
  become: false
  notify: Restart mqtt

# TODO: The first time this playbook is run, the `pi` user may not be added
# to the `docker` group, so this task may fail.
- name: Ensure mqtt is running.
  community.docker.docker_compose_v2:
    project_src: "{{ config_dir }}/mqtt/"
    build: never
  become: false
