---
- name: Ensure timescaledb directory exists.
  ansible.builtin.file:
    path: "{{ config_dir }}/timescaledb"
    state: directory
    mode: 0755
  become: false

- name: Copy timescaledb docker-compose template to Pi.
  ansible.builtin.template:
    src: templates/timescaledb-docker-compose.yml.j2
    dest: "{{ config_dir }}/timescaledb/docker-compose.yml"
    mode: "0640"
  become: false
  notify: Restart timescaledb

# TODO: The first time this playbook is run, the `pi` user may not be added
# to the `docker` group, so this task may fail.
- name: Ensure timescaledb is running.
  community.docker.docker_compose_v2:
    project_src: "{{ config_dir }}/timescaledb/"
    build: never
  become: false
