---
- name: Ensure Traefik directory exists.
  ansible.builtin.file:
    path: "{{ config_dir }}/traefik"
    state: directory
    mode: 0755
  become: false

- name: Copy Traefik docker-compose template to Pi.
  ansible.builtin.template:
    src: templates/traefik-docker-compose.yml.j2
    dest: "{{ config_dir }}/traefik/docker-compose.yml"
    mode: "0640"
  become: false
  notify: Restart traefik

- name: Ensure Traefik is running.
  community.docker.docker_compose_v2:
    project_src: "{{ config_dir }}/traefik/"
    build: never
  become: false
